### ISSUE TITLE
Dataset Link Not working 

### ISSUE THREAD

**Issue by muhammadwaqas476074** [makramchahine/drone_causality#3]
Hello @makramchahine the links available in the readme for the dataset are not working is there any other way to get the dataset.

**Comment by makramchahine** [comment]
Hello indeed the link is dead here is the replacement sorry for the delay 
https://www.dropbox.com/scl/fo/6kwdqxh4hixwt4542xbrf/AIr0yx-bFF5y5CCdxHHOj8Q?rlkey=m7u5omps9og1k5sdee698vfq5&st=t8z5jw51&dl=0
