### ISSUE TITLE
Help: Dataset link can't open.

### ISSUE THREAD

**Issue by hddchelsea** [makramchahine/drone_causality#5]
Hello, I also want to run the code, but the dataset link is none, it means http://knightridermit.myqnapcloud.com:8080/share.cgi?ssid=06lMJMN&fid=06lMJMN is lost, and can you send dataset. 
Thank you very much!

**Comment by makramchahine** [comment]
Hello, the dataset was previously updated in the readme, pasted here for your convenience 

https://www.dropbox.com/scl/fo/6kwdqxh4hixwt4542xbrf/AIr0yx-bFF5y5CCdxHHOj8Q?rlkey=m7u5omps9og1k5sdee698vfq5&st=t8z5jw51&dl=0

**Comment by hddchelsea** [comment]
Thanks!!!
